### ISSUE TITLE
Linux OC version - ./init.sh: 76: [: v3: unexpected operator

### ISSUE THREAD

**Issue by jamesbuckett** [redhatdemocentral/ocp-install-demo#10]
Hello.

wget https://s3.amazonaws.com/oso-preview-docker-registry/client-tools/3.3/oc-3.3.0.35-1-linux.tar.gz

tar -xvf oc-3.3.0.35-1-linux.tar.gz

mv oc /usr/bin/oc

`root@ubuntu-1gb-sfo1-01:~/ocp/ocp-install-demo-master# oc version
oc v3.3.0.35
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO`

When I run ./init.sh

`##############################################################
##############################################################

./init.sh: 41: [: Linux: unexpected operator
Docker is installed... checking for valid version...

Valid version of docker engine found... 1.12

OpenShift command line tools installed... checking for valid version...

./init.sh: 76: [: v3: unexpected operator
Version of installed OpenShift command line tools is v3.3, must be v3.3 or higher...

Download for Linux here: https://s3.amazonaws.com/oso-preview-docker-registry/client-tools/3.3/oc-3.3.0.35-1-linux.tar.gz
Download for Mac here: https://s3.amazonaws.com/oso-preview-docker-registry/client-tools/3.3/oc-3.3.1.3-1-macosx.tar.gz
`
Could be this line in init.sh `OC_MAJOR_VER="v3"`

**Comment by eschabell** [comment]
Yes, that is odd as the version linked to used this OCP setup produces this:

$ oc version
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth
error: server took too long to respond with version information.

If you comment out the lines that check for the OC version (from line 72-86), does this 3.3.0.x version work? I am trying to determine if you need 3.3.x or 3.3.1+ before fixing the problem you have encountered.

Thanks for the feedback.

**Comment by eschabell** [comment]
Open if still an issue, provide feedback to question asked...
