### ISSUE TITLE
dial tcp 209.132.182.63:443: i/o timeout on running init.sh

### ISSUE THREAD

**Issue by ffirg** [redhatdemocentral/ocp-install-demo#11]
Phils-MBP:ocp-install-demo-master pgriffit$ ./init.sh

##############################################################
##############################################################

VirtualBox is installed...

Docker is installed... checking for valid version...

Valid version of docker engine found... 1.12

OpenShift command line tools installed... checking for valid version...

error: server took too long to respond with version information.
Version of installed OpenShift command line tools correct... v3.3.1.3

Installing OCP with cluster up...

Using osX version of cluster up... oc version: v3.3.1.3

-- Checking OpenShift client ... OK
-- Create Docker machine ...
   Creating docker-machine openshift
FAIL
   Error: Docker machine exists

Error occurred during oc cluster up command!

Cleaning out existing openshift machine.

About to remove openshift
Successfully removed openshift

Trying again to install OSE with cluster up...

Using osX version of cluster up... oc version: v3.3.1.3

-- Checking OpenShift client ... OK
-- Create Docker machine ...
   Creating docker-machine openshift
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.3.1.3 image ...
   Pulling image registry.access.redhat.com/openshift3/ose:v3.3.1.3
FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.3.1.3
   Caused By:
     Error: API error (500): {"message":"Get https://registry.access.redhat.com/v1/_ping: dial tcp 209.132.182.63:443: i/o timeout"}

**Comment by jamesfalkner** [comment]
I think it was temporarily down - works for me now.

**Comment by eschabell** [comment]
Yep, thanks @jamesfalkner, was going to suggest the same... timeouts happen means try again... it's not you!

**Comment by ffirg** [comment]
Thanks. Yes openshift-sme suggests that an F5 LB was an issue. 
I yes getting a different error now but have deleted the docker-machine and I’m retrying.
If it’s still a problem I’ll raise another one.
