### ISSUE TITLE
The docker version should be 1.12 in OCP3.4/Origin1.4.

### ISSUE THREAD

**Issue by warmchang** [redhatdemocentral/ocp-install-demo#13]
ocp-install-demo/init.sh, DOCKER_MINOR_VER should be 12.
https://docs.openshift.com/container-platform/3.4/install_config/install/host_preparation.html#installing-docker
https://docs.openshift.org/latest/install_config/install/host_preparation.html#installing-docker

**Comment by warmchang** [comment]
oops, this demo run ocp by "oc cluster up", so the docker version 1.10 is enough.
close it, sorry. :-)

**Comment by eschabell** [comment]
Thanks, no worries, best issues are the self-closing and self-teaching ones! :-)
