### ISSUE TITLE
error installing ocp

### ISSUE THREAD

**Issue by babluchandran** [redhatdemocentral/ocp-install-demo#14]
Tried installing ocp in rhel7 with docker version 1.13 and oc version 3.4.1.2-1.
Getting the below error when i run the **./init.sh** file.
**-- Checking Docker daemon configuration ... FAIL
   Error: did not detect an --insecure-registry argument on the Docker daemon
   Solution:

     Ensure that the Docker daemon is running with the following argument:
        --insecure-registry 172.30.0.0/16
Problem with installation that I can't resolve, please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new**

**Comment by babluchandran** [comment]
I followed the instructions in this link to add insecure registry....
https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux
Still facing the same error.

**Comment by eschabell** [comment]
If your fixes do not work as described in the OpenShift Origin (that uses just 'oc cluster up') then it will not work here either. Make sure your firewall and insecure registries are setup to work with just command line 'oc cluster up'. 

If that works and then it fails here, please report the console output here.

**Comment by eschabell** [comment]
Closing due to lack of input and need to retest with updated version 3.4.
