### ISSUE TITLE
Business Central war fails to deploy

### ISSUE THREAD

**Issue by eschabell** [redhatdemocentral/ocp-install-demo#15]
On container EAP start, right at end:

09:55:37,971 INFO [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found business-central.war in deployment directory. To trigger deployment create a file called business-central.war.dodeploy

Since when do we need a 'dodeploy'?

**Comment by sabre1041** [comment]
@eschabell this demo does not deploy any applications. Did you deploy an application after standing up the demo?

Business central is delivered and deployed as an exploded war. EAP will not deploy exploded wars unless there is a .dodeploy marker file

**Comment by eschabell** [comment]
I know, just unzipping the product, nothing added, but this is how it was always done, nothing new here other than adding these:

&& sed -i 's/ExampleDS/PostgresDS/g' $BRMS_HOME/standalone/deployments/business-central.war/WEB-INF/classes/META-INF/persistence.xml \
  && sed -i 's/H2Dialect/PostgreSQLDialect/g' $BRMS_HOME/standalone/deployments/business-central.war/WEB-INF/classes/META-INF/persistence.xml \
  && sed -i 's/H2Dialect/PostgreSQLDialect/g' $BRMS_HOME/standalone/deployments/business-central.war/WEB-INF/classes/META-INF/persistence.xml \

Does this mean possible permission problems cause this not to deploy?

**Comment by eschabell** [comment]
Wait, posted to wrong demo.... closing and moving.
