### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by starksm64** [redhatdemocentral/ocp-install-demo#16]
I'm going through the installation described at http://www.schabell.org/2017/02/cloud-happiness-openshift-container-platform-install-updated.html, and it is reporting a failure:

##############################################################
##############################################################

Docker is installed... checking for valid version...

Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Valid version of docker engine found... 1.10

OpenShift command line tools installed... checking for valid version...

error: server took too long to respond with version information.
Version of installed OpenShift command line tools correct... v3.4.1.2

Installing OCP with cluster up...

Using Linux version of cluster up... installing OCP version: v3.4

-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     Ensure that Docker is installed and accessible in your environment.
     Use your package manager or follow instructions at:

        https://docs.docker.com/linux/

   Caused By:
     Error: Get http://unix.sock/_ping: dial unix /var/run/docker.sock: connect: permission denied

Error occurred during oc cluster up command!

Cleaning out existing openshift machine.

./init.sh: line 116: docker-machine: command not found

Trying again to install OSE with cluster up...

Using Linux version of cluster up... installing second try OCP version: v3.4

-- Checking OpenShift client ... OK
-- Checking Docker client ... FAIL
   Error: cannot communicate with Docker
   Solution:

     Ensure that Docker is installed and accessible in your environment.
     Use your package manager or follow instructions at:

        https://docs.docker.com/linux/

   Caused By:
     Error: Get http://unix.sock/_ping: dial unix /var/run/docker.sock: connect: permission denied

Problem with installation that I can't resolve, please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new
[sstark@sstark ocp-install-demo-master]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.2 (Maipo)
[sstark@sstark ocp-install-demo-master]$ uname -a
Linux sstark.remote.csb 3.10.0-327.18.2.el7.x86_64 #1 SMP Fri Apr 8 05:09:53 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by starksm64** [comment]
That particular failure appears to be due to not going through the docker post install step to allow docker to run without using sudo. After doing that, it was also required to add --insecure-registry option to the /usr/lib/systemd/system/docker.service script in order to have the init.sh script succeed.

**Comment by eschabell** [comment]
Yes, this is not something I can block on, but maybe add a more prominent warning for Linux users at the start..... much more than that I can't do as the docker check is only for versions. 

@starksm64: Do you have any suggestions on how to check for docker running correctly on Linux?

**Comment by eschabell** [comment]
Think I found a good way to validate deamon presence for OS X and Linux... please verify and reopen if needed. Fixed by https://github.com/redhatdemocentral/ocp-install-demo/commit/1b9f35066dfbd97b79e23b8d7c4e48892beb78f3
