### ISSUE TITLE
enable metrics

### ISSUE THREAD

**Issue by sudheerchekka** [redhatdemocentral/ocp-install-demo#18]
adding --metrics option to "oc custer up" in init.sh to enable metrics is not working. any recommendations how to enable metrics for this demo ?

**Comment by eschabell** [comment]
If you have ideas on how to do this with limited resources (this demo targets local laptop usage), then I am all ears. 

I have worked with @sabre1041 in the past to try and put this together here: https://github.com/sabre1041/rhcs-metrics-demo

It is pretty resource intensive, so decided against targeting this for this project. I will close this but remain open to a solution that works well on less than 16GB RAM machines. ;-)

Btw, is the current version here of 'oc' not using : --metrics=true

**Comment by eschabell** [comment]
I did play with the --metrics=true option and get metrics on container deployments, but they don't seem to work... see attached image.
<img width="524" alt="screen shot 2017-02-24 at 2 47 24 pm" src="https://cloud.githubusercontent.com/assets/437001/23305678/4703b4fa-faa0-11e6-903c-984380a75d4e.png">
