### ISSUE TITLE
Docker Registry error

### ISSUE THREAD

**Issue by steven-ellis** [redhatdemocentral/ocp-install-demo#21]
Error: did not detect an --insecure-registry argument on the Docker daemon
   Solution:

     Ensure that the Docker daemon is running with the following argument:
     	--insecure-registry 172.30.0.0/16

The client is RHEL 7.3 with a clean docker install.

**Comment by steven-ellis** [comment]
Need to add 
INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
to /etc/sysconfig/docker and restart docker service.

**Comment by eschabell** [comment]
Fixed in https://github.com/redhatdemocentral/ocp-install-demo/commit/15dc4a0c2a2049feea3641434da4d31d602ba042
