### ISSUE TITLE
Docker Machine missing on Fedora - manual installation required

### ISSUE THREAD

**Issue by vinicius-martinez** [redhatdemocentral/ocp-install-demo#25]
Docker is installed... checking for valid version...

Verified the Docker deamon is running...

In order to successfully install ocp using this procedure on f25, you have to meet the following requirements:

- Docker Community Edition

sudo dnf -y install dnf-plugins-core

sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

sudo dnf makecache fast

sudo dnf -y install docker-ce

Start Docker:

sudo systemctl start docker or sudo service docker start

Testing

sudo docker run hello-world

# https://store.docker.com/editions/community/docker-ce-server-fedora

- Docker Machine manual installation

curl -L https://github.com/docker/machine/releases/download/v0.10.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
  chmod +x /tmp/docker-machine &&
  sudo cp /tmp/docker-machine /usr/local/bin/docker-machine

# https://docs.docker.com/machine/install-machine/

If you do not install docker-machine manually, the following error message will be displayed:

OpenShift command line tools installed... checking for valid version...

Version of installed OpenShift command line tools correct... v3.5.5

Setting up OpenShift docker machine...

./init.sh: line 126: docker-machine: command not found

Error occurred during openshift docker machine creation...

Cleaning out existing 'openshift' machine...

./init.sh: line 134: docker-machine: command not found
Setting up new OpenShift docker machine...

./init.sh: line 138: docker-machine: command not found

Problem with docker machine creation that I can't resolve, please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new

**Comment by eschabell** [comment]
There is literally no way to capture all possible Linux variations to install docker.... for the workshop I give around this demo installation Linux is covered by going to the current documentation for the distro you are running.

Not sure what you want me to fix for your issue?

**Comment by vinicius-martinez** [comment]
Not sure if you should add a  "pre reqs" section adding those required binaries.  Does it make sense for you ?

I've just filled this issue due the "error message" that's displayed after the installation failure:

```
Problem with docker machine creation that I can't resolve, please raise an issue and add error output:

https://github.com/redhatdemocentral/ocp-install-demo/issues/new

```
Feel free to close =)

Best regards,

**Comment by eschabell** [comment]
There is a pre-req... and yes, please always file everything.... this is just one if the ones I have to leave to Linux users to sort out themselves. From the readme I updated this week: 

Pro Tip: Pay close attention to conosle output, will guide you to dependencies you need if missing. These dependencies are listed here and the install provides pointers to downloads if missing:

1. VirtualBox for Windows and OSX
2. Docker engine version 17.03
3. OpenShift Client (oc) v3.5.5.5
