### ISSUE TITLE
logging is admin

### ISSUE THREAD

**Issue by ishuverma** [redhatdemocentral/ocp-install-demo#26]
oc login -u admin:admin doesn't seem to be working as it assumes user to be admin:admin

**Comment by eschabell** [comment]
Pretty bleak bug report... you tried to us 'oc login -u admin:admin' after installing ocp-install-demo? The console output states that you can use 'oc' as follows:

oc login -u system:admin

Are you confusing the OpenShift Container Platform web console login with 'oc' logins?

**Comment by ishuverma** [comment]
No, but it got resolved so closing the issue
