### ISSUE TITLE
Cannot Download OC command line tool v3.6.173 needed for this demo.

### ISSUE THREAD

**Issue by sg1970** [redhatdemocentral/ocp-install-demo#28]
Trying to get this working --> https://github.com/redhatdemocentral/ocp-install-demo

When I run the init.bat file I get the error : **Version of installed OpenShift command line tools is v3.6.0-rc, must be v3.6.173**... and  it asks me to Download the **oc.exe** client  for Windows from here: https://access.redhat.com/downloads/content/290

However that link requires a paid subscription (Please correct me if wrong).  Is the free version of 3.6.173 not available yet ?

Thanks!

**Comment by eschabell** [comment]
Yes, you need a login for this oc version at the red hat portal. If you [contact me directly](http://www.schabell.org/p/contact.html) I can provide a trial version.
