### ISSUE TITLE
no db templates loaded

### ISSUE THREAD

**Issue by rbaumgar** [redhatdemocentral/ocp-install-demo#31]
Eric,

I am missing the DB examples from https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_examples/files/examples/v3.6/db-templates

Kind regards 
Robert

**Comment by rbaumgar** [comment]
It looks like it was a problem of my environment. I enable the new service brocker with --service-catalog, but I didn't
oc adm policy add-cluster-role-to-group system:openshift:templateservicebroker-client system:unauthenticated system:authenticated

After that I have to logout and login...

**Comment by eschabell** [comment]
So are the db's available out of the box? Or do I need to add a stream?

**Comment by rbaumgar** [comment]
It looks like it was a problem of my environment. I enable the new service brocker with --service-catalog, but I didn't
oc adm policy add-cluster-role-to-group system:openshift:templateservicebroker-client system:unauthenticated system:authenticated

After that I have to logout and login...

**Comment by rbaumgar** [comment]
The templates are available OOTB - only the ephemeral are missed. 
But after restart (ocp-restart) the db templates are not shown again. But I can find it still in project openshift.

**Comment by eschabell** [comment]
When you initially start this up (install), you need to give it enough time to pull in all the imagestreams and templates.... try that first.

If something still is missing, let me know what you need added?

**Comment by eschabell** [comment]
I just double checked mine, under CATOLOG -> DATA STORES I have (17*3+1) entries and they seem to work fine when I click and fill in the sample projects. Feels like your image streams are just not done pulling or are not pulling correctly?

I have not added any of the co commands you list above, including your policy line above.

**Comment by eschabell** [comment]
I will do some testing with the catalog switch and make sure everything still working... stay tuned.

**Comment by eschabell** [comment]
Tagged new release v1.9 of this project with tech preview catalog enabled.

**Comment by amandadebler** [comment]
@eschabell There are typos in init.bat in the Fuse image streams section (lines 240 and 248): "ttps://" instead of "https://"

**Comment by eschabell** [comment]
@amandadebler thanks, fixed it.
