### ISSUE TITLE
Service Catalog is not getting started, OCP failed

### ISSUE THREAD

**Issue by gjayaram** [redhatdemocentral/ocp-install-demo#32]
Not able to start the OCP server, service catalog failed...

Tried with both versions of OC client (3.6.173.0.5) and 3.6.173.0.21.

The below issue is coming with 3.6.173.0.5, if i use 3.6.173.0.21 then the system is got struck at pulling images from registry.

gjayaram$ oc version
oc v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://192.168.99.100:8443
kubernetes v1.6.1+5115d708d7

 gjayaram$ ./init.sh
##############################################################
##  Setting up your very own                                ##
......
......
......
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.6 ...
Pulling image registry.access.redhat.com/openshift3/ose:v3.6
Pulled 1/4 layers, 25% complete
Pulled 1/4 layers, 25% complete
Pulled 1/4 layers, 25% complete
Pulled 1/4 layers, 25% complete
Pulled 1/4 layers, 25% complete
Pulled 1/4 layers, 25% complete
Pulled 1/4 layers, 25% complete
Pulled 2/4 layers, 50% complete
Pulled 2/4 layers, 50% complete
Pulled 3/4 layers, 75% complete
Pulled 3/4 layers, 75% complete
Pulled 3/4 layers, 75% complete
Pulled 4/4 layers, 100% complete
Extracting
Image pull complete
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.6 image ... 
   Pulling image registry.access.redhat.com/openshift3/ose:v3.6
   Pulled 1/4 layers, 25% complete
   Pulled 1/4 layers, 25% complete
   Pulled 1/4 layers, 25% complete
   Pulled 1/4 layers, 25% complete
   Pulled 1/4 layers, 25% complete
   Pulled 1/4 layers, 25% complete
   Pulled 1/4 layers, 25% complete
   Pulled 2/4 layers, 50% complete
   Pulled 2/4 layers, 50% complete
   Pulled 3/4 layers, 75% complete
   Pulled 3/4 layers, 75% complete
   Pulled 3/4 layers, 75% complete
   Pulled 4/4 layers, 100% complete
   Extracting
   Image pull complete
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ... 
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ... 
   Using docker-machine IP 192.168.99.100 as the host IP
   Using 192.168.99.100 as the server IP
-- Checking service catalog version requirements ... OK
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
FAIL
   Error: could not start OpenShift container "origin"
   Details:
     No log available from "origin" container

**Comment by eschabell** [comment]
I can tell you that using v3.6.173.0.5 will always end the way you have seen it. If you run it with the v3.6.173.0.21 I think it might come out differently. Getting stuck on pulling images is probably a networking issue that should go away (your bandwidth is good?).

Try and let me know what you get?

**Comment by gjayaram** [comment]
@eschabell thanks it worked with v3.6.173.0.21.
