### ISSUE TITLE
 cannot set up guest memory 'pc.ram': Cannot allocate memory'

### ISSUE THREAD

**Issue by vhalbert** [redhatdemocentral/ocp-install-demo#35]
(openshift) Creating SSH key...
(openshift) Failed to start: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2017-09-29T12:54:42.748222Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory')
Error creating machine: Error in driver during machine creation: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2017-09-29T12:54:42.748222Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory')

**Comment by eschabell** [comment]
How much RAM are you allocating (see variable at top of init.sh or init.bat), do you have enough on your machine? 

Default is 8GB but I have run this with 6GB many times.

**Comment by vhalbert** [comment]
I have a 16gb machine, but was already using just over 8.  So I changed the init.sh to:  VM_MEMORY=6144

and it all has finished.  I can now access the OS catalog.

Thanks.
