### ISSUE TITLE
Required active subscription to download OpenShift CLI

### ISSUE THREAD

**Issue by leonboxboat** [redhatdemocentral/ocp-install-demo#36]
Hi, and thanks for putting this together.

In your lightning talk you mention only needing a laptop and connection, and not having to login to RedHat Developers to be able to get the ImageStreams, but I am still required to have an active subscription to download the OpenShift CLI. 

Is this intentional? Is the CLI outside the scope? Because IMHO it kind of goes contrary to the purpose of this repo to simplify things.

In my case, my trial license expired and I can't get a new one until November, so does that mean I am locked out from being able to try this? And does this mean then that each developer would need to have an active login to be able to download the CLI?

If I try to use the latest Origin CLI tools I get an error:

![image](https://user-images.githubusercontent.com/26549797/31855631-df413ac4-b67c-11e7-8c87-1c182f0fea68.png)

**Comment by eschabell** [comment]
In the accompanying workshop there is a note to contact me if you have issues with access to the OC client... if you mail erics at red hat dot com I can help you.
