### ISSUE TITLE
Windows 10 Docker CE runs on Hyper-V... breaks VirtualBox

### ISSUE THREAD

**Issue by betazep** [redhatdemocentral/ocp-install-demo#38]
Docker for Windows requires Hyper-V now.  Hyper-V disables VirtualBox. Your demo requires Virtual Box.

Have time to make this work on Windows using Docker Toolbox so that VirtualBox will work?
https://www.docker.com/products/docker-toolbox

**Comment by eschabell** [comment]
I actually am working with a group that uses Windows 7 and they use Docker Toolbox, which is fine as a replacement, but they are having NAT issues between Windows 7 and VirtualBox.

I would be interested in your experience with Windows 10 using this?

**Comment by betazep** [comment]
Hi Eric...

I think I have it working in HyperV by adjusting your windows script (docker-machine driver, typos, etc) and changing default network vswitch configuration for DockerNAT.  I will delete everything, recreate, re-run to ensure overwrite and provide updated script/instructions here.  

Sean

**Comment by eschabell** [comment]
@betazep my hero... we await your PR (and don't forget to add your name to the contributors variable in the init.bat... you earned it with this work)!

**Comment by betazep** [comment]
### Use or change as you see fit... this is essentially what I did...  Thank you for providing these demos! 
### ~ Sean
------------------------------------------
Windows 10 Instructions
1. Install OpenShift Client.
2. Install Docker for Windows (17.09+) with Hyper-V
3. Run Docker for Windows. This will require/install Hyper-V and will disable VirtualBox, Docker Toolbox, and/or VMware Workstation!
4. *Important* - Use Hyper-V Manager to create "ocpNET" Virtual Switch. (name is used in script) 
5. *Important* - Set "ocpNET" to External Network physical/wireless interface (with DHCP) - Must have Internet.
6. Open CMD Prompt as Administrator and run init-Win10.bat.
7. Follow displayed instructions to log in to your brand new OpenShift Container Platform!
-------------------------------------
[init-win10.bat.txt](https://github.com/redhatdemocentral/ocp-install-demo/files/1451589/init-win10.bat.txt)
(rename to *.bat extension)

**Comment by betazep** [comment]
I can do this thru PR tomorrow.

**Comment by eschabell** [comment]
Merge commit https://github.com/redhatdemocentral/ocp-install-demo/commit/6f2399969feae5ea6ccdc8f8c889bb00ccbe5b40 fixes.
