### ISSUE TITLE
Reinstallation error.

### ISSUE THREAD

**Issue by Sprbb** [redhatdemocentral/ocp-install-demo#40]
Remove ocp-install-demo and install again. Unfortunately I got the follwing error while reinstalling:

(openshift) Creating VHD
Error creating machine: Error in driver during machine creation: exit status 1

Error occurred during openshift docker machine creation...

Cleaning out existing 'openshift' machine...

About to remove openshift
WARNING: This action will delete both local reference and remote instance.
Can't remove "openshift"
Setting up new OpenShift docker machine...
Host already exists: "openshift"

**Comment by eschabell** [comment]
There will be some way to remove the VM, via VirtualBox in Mac, via KVM in Linux and whatever the VM Manager is in Hyper-V if Windows system. See if you can find it and remove the 'openshift' named VM.

**Comment by Sprbb** [comment]
Yes it works again !!!
