### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by bhandaru** [redhatdemocentral/ocp-install-demo#41]
Hello,

I'm running this on mac with docker 17.09, oc 3.6.173 and have 172.30.0.0/16 added to the insecure-registry list on docker.

I get the following error when JBoss image is being created

```Unable to connect to the server: net/http: TLS handshake timeout```

What am I missing?

**Comment by eschabell** [comment]
This is usually due to using an oc client with number v3.6.173.05 and you need v3.6.173.21. 

$ oc version

oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Btw, just update this project to deliver OpenShift Container Platform v3.7, so the oc client would then need to be v3.7.9.
