### ISSUE TITLE
Missing decision server 6.3 in OCP 3.7 xpaas streams

### ISSUE THREAD

**Issue by eschabell** [redhatdemocentral/ocp-install-demo#42]
error: unable to read URL
"https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.7/xpaas-templates/decisionserver63-basic-s2i.json",
server reported 404 Not Found, status code=404

**Comment by eschabell** [comment]
Immediate fix is to use this after installation, first logging in and then pulling the xpaas tempate shown:

$ oc login -u system:admin

$ oc create -n openshift -f https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.6/xpaas-templates/decisionserver63-basic-s2i.json

**Comment by Sprbb** [comment]
Tnx for your fast reply.

-- 
Graag ontvang ik een bevestiging retour.

Met vriendelijke groet,

Bas Neve
bastiaanneve@gmail.com
316 14 12 00 71




2017-12-11 9:53 GMT+01:00 Eric D. Schabell <notifications@github.com>:
