### ISSUE TITLE
3.7still asks for boot2docker.iso.

### ISSUE THREAD

**Issue by Sprbb** [redhatdemocentral/ocp-install-demo#46]
Error occurred during openshift docker machine creation...

Cleaning out existing 'openshift' machine...

About to remove openshift
WARNING: This action will delete both local reference and remote instance.
(openshift) Failed to fetch machine
Error removing host "openshift": unexpected EOF
Successfully removed openshift
Setting up OpenShift docker machine using kvm...

Running pre-create checks...
Creating machine...
(openshift) Downloading /home/bas/.docker/machine/cache/boot2docker.iso from file:///home/bas/.docker/machine/cache/boot2docker.iso...
Error creating machine: Error in driver during machine creation: open /home/bas/.docker/machine/cache/boot2docker.iso: no such file or directory

Problem with docker machine creation that I can't resolve, please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new

[bas@DESKTOP-CFKC4SB ocp-install-demo-master]$

**Comment by eschabell** [comment]
This is an issue, seems the fallback from cache is to look for cache again, should be looking to download if cache missing.
