### ISSUE TITLE
getting dial tcp: missing address error

### ISSUE THREAD

**Issue by parthashp** [redhatdemocentral/ocp-install-demo#47]
I am trying to setup OCP in RHEL 7.4 and getting below error. Could you please help me to resole this one?

You are running on Linux.
This script assumes you are going to use KVM on Linux.
You'll need to install docker-machine and docker-machine-driver-kvm in your $PATH manually.
Download them from https://github.com/docker/machine/releases and https://github.com/dhiltgen/docker-machine-kvm/releases, respectively.
Docker-machine tooling installed...

OpenShift command line tools installed... checking for valid version...

Version of installed OpenShift command line tools correct... v3.7.9

Setting up OpenShift docker machine using kvm...

dial tcp: missing address

Error occurred during openshift docker machine creation...

Cleaning out existing 'openshift' machine...

About to remove openshift
WARNING: This action will delete both local reference and remote instance.
Error removing host "openshift": Docker machine "openshift" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
Can't remove "openshift"
Setting up OpenShift docker machine using kvm...

dial tcp: missing address

Problem with docker machine creation that I can't resolve, please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new

**Comment by Sprbb** [comment]
Please give all output. from $ and so on.


2017-12-31 7:52 GMT+01:00 parthashp <notifications@github.com>:

**Comment by eschabell** [comment]
@parthashp, I think you might be missing the entry for insecure registry.... used to be part of the Docker engine configuration when you ran it as a daemon, but not sure how to adjust for the docker-machine command being run on KVM. 

Maybe investigate in the direction of looking at how to add that in the config or command that creates your docker-machine KVM image?

Hints are give here in the docs: 

https://docs.docker.com/machine/reference/create/#accessing-driver-specific-flags-in-the-help-text

I will have to look at this after New Years closer if you can't find it, so let me know what you come up with?

**Comment by eschabell** [comment]
Assume works as not reply, reopen if need to.
