### ISSUE TITLE
Error restarting the cluster - cert issue

### ISSUE THREAD

**Issue by cgsk123** [redhatdemocentral/ocp-install-demo#49]
After installing the OCP cluster on Windows 10, if you restart the docker-machine.

It throws below error
```
NAME        ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER    ERRORS
openshift   -        hyperv   Running   tcp://192.168.0.17:2376           Unknown   Unable to query docker version: Get https://192.168.0.17:2376/v1.15/version: x509: certificate is valid for 192.168.0.16, not 192.168.0.17      
```                                                                                                                                    

To fix the issue, i used

```
docker-machine regenerate-certs openshift
docker-machine env openshift
@FOR /f "tokens=*" %i IN ('docker-machine env openshift') DO @%i
```

Then the error goes off. But could not 'oc login', it throws
```
oc login 192.168.0.17:8443
error: dial tcp 192.168.0.17:8443: connectex: No connection could be made because the target machine actively refused it. - verify you have provided the correct host and port and that the server is currently running.

```
how to fix the issue? it seems whenever i restart my laptop totally cluster/docker-machine is in a corrupt status.

How to install once the cluster/docker-machine and use it without facing issue in laptop shutdown.

**Comment by eschabell** [comment]
Bringing in @betazep as our resident Hyper-V expert. 

@betazep, can you help?

**Comment by betazep** [comment]
Hmmm...  well this appears to be less of a Hyper-V/docker-machine based issue and more about how OCP configured for a specific top end IP address and nip.io DNS name can handle an IP address change.  I am curious how it behaves when the same IP address is used after a restart.   Whenever I needed to run a demo... I just deployed a fresh environment.  I can say that "deploying new" is a much easier approach than what it will probably take to reconfigure the demo to use different master and wildcard dns names than what it was deployed with.  I probably have a few cycles today.  I will investigate a little, but this one probably needs a more experienced brain than mine.  I only started with OCP three months ago.  :)

**Comment by betazep** [comment]
So when the docker-machine (openshift) is restarted, the cluster doesn't come back up.  You have to bring it back up again.  With the same IP address, you can bring the cluster back up with:

`oc cluster up --image=registry.access.redhat.com/openshift3/ose --host-data-dir=/var/lib/boot2docker/ocp-data  --docker-machine=openshift --host-config-dir=/var/lib/boot2docker/ocp-config --use-existing-config=true --host-pv-dir=/var/lib/boot2docker/ocp-pv --service-catalog`

I restarted it through a couple means.
     First: **docker-machine restart openshift**
     Second: Just shutdown in Hyper-V manager.
In both cases, I was able to recover.  I am going to turn off my computer and try to get a new IP tomorrow.  (DHCP leases at work are quite long).  In the meantime, maybe you can describe what happens when you do your cert fix and then run the **oc cluster up** command above.

**Comment by cgsk123** [comment]
The intention was to retain the OCP cluster is to play with it and i hate to lose my demo work whenever i restart my laptop or restart the docker-machine 

```
Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\senth>docker-machine ls
NAME        ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER    ERRORS
openshift   -        hyperv   Running   tcp://192.168.0.20:2376           Unknown   Unable to query docker version: Get https://192.168.0.20:2376/v1.15/version: x509: certificate is valid for 192.168.0.17, not 192.168.0.20

C:\Users\senth>docker-machine regenerate-certs openshift
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

C:\Users\senth>docker-machine ls
NAME        ACTIVE   DRIVER   STATE     URL                       SWARM   DOCKER    ERRORS
openshift   -        hyperv   Running   tcp://192.168.0.20:2376           v1.13.1

C:\Users\senth>docker-machine env openshift
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.0.20:2376
SET DOCKER_CERT_PATH=C:\Users\senth\.docker\machine\machines\openshift
SET DOCKER_MACHINE_NAME=openshift
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('docker-machine env openshift') DO @%i

C:\Users\senth>@FOR /f "tokens=*" %i IN ('docker-machine env openshift') DO @%i

C:\Users\senth>oc login 192.168.0.20:8443
error: dial tcp 192.168.0.20:8443: connectex: No connection could be made because the target machine actively refused it. - verify you have provided the correct host and port and that the server is currently running.

C:\Users\senth>oc cluster up --image=registry.access.redhat.com/openshift3/ose --host-data-dir=/var/lib/boot2docker/ocp-data --docker-machine=openshift --host-config-dir=/var/lib/boot2docker/ocp-config --use-existing-config=true --host-pv-dir=/var/lib/boot2docker/ocp-pv --service-catalog
Starting OpenShift using registry.access.redhat.com/openshift3/ose:v3.7.9 ...
-- Checking OpenShift client ... OK
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ...
   Deleted existing OpenShift container
-- Checking for registry.access.redhat.com/openshift3/ose:v3.7.9 image ... OK
-- Checking Docker daemon configuration ... OK
-- Checking for available ports ... OK
-- Checking type of volume mount ...
   Using Docker shared volumes for OpenShift volumes
-- Creating host directories ... OK
-- Finding server IP ...
   Using docker-machine IP 192.168.0.20 as the host IP
   Using 192.168.0.20 as the server IP
-- Checking service catalog version requirements ... OK
-- Starting OpenShift container ...
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
FAIL
   Error: cannot access master readiness URL https://192.168.0.20:8443/healthz/ready
   Details:
     Last 10 lines of "origin" container log:
     I0320 08:35:22.308011   22450 apiservice_controller.go:113] Starting APIServiceRegistrationController
     I0320 08:35:22.308516   22450 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
     I0320 08:35:22.308602   22450 tprregistration_controller.go:147] Starting tpr-autoregister controller
     I0320 08:35:22.308651   22450 controller_utils.go:1025] Waiting for caches to sync for tpr-autoregister controller
     I0320 08:35:22.309801   22450 available_controller.go:256] Starting AvailableConditionController
     I0320 08:35:22.309863   22450 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
     I0320 08:35:22.310229   22450 customresource_discovery_controller.go:152] Starting DiscoveryController
     I0320 08:35:22.310281   22450 naming_controller.go:284] Starting NamingConditionController
     I0320 08:35:22.322622   22450 autoregister_controller.go:141] Starting autoregister controller
     I0320 08:35:22.330128   22450 cache.go:32] Waiting for caches to sync for autoregister controller


   Caused By:
     Error: Get https://192.168.0.20:8443/healthz/ready: x509: certificate is valid for 127.0.0.1, 172.17.0.1, 172.30.0.1, 192.168.0.16, not 192.168.0.20

C:\Users\senth>

```

**Comment by betazep** [comment]
Yeah... pretty much what I thought would happen.  I guess there are two options. 
1. Get a static IP going in the docker-machine host.
2. Figure out everything that needs to change in OCP due to an IP change (which all services reside on in a single machine deployment). Obviously certs would have to be regenerated inside OCP as well.

The second one exceeds my ability at the moment.  I don't know the answer, and for a demo system (or a production one) I wouldn't generally change the IP.  So unless @eschabell has some insight here, I don't know if this path will resolve.

For the first one, you can just follow something like this... (performed after initial install to ensure IP stays the same on subsequent reboots)
https://www.prkz.de/blog/10-make-docker-machine-docker-host-use-a-static-ip-address

Note: I haven't tested this yet, but I will when I get into the office because I want to see if it works for certain.

**Comment by eschabell** [comment]
This is indeed a demo environment and don't plan to facilitate the described IP updates.

**Comment by cgsk123** [comment]
@betazep Thanks ... static IP approach worked
**Steps:** 
1. Fresh Install using the init script example init-win10.bat
2. Get the ip of the docker-machine (example: 192.168.0.30) 
3. After the install, ssh into(docker-machine ssh openshift) and (create)modify the /var/lib/boot2docker.sh 
Get the other ips from your host os ipconfig
```
docker@openshift:~$ sudo -i
Boot2Docker version 1.13.1, build HEAD : b7f6033 - Wed Feb  8 20:31:48 UTC 2017
Docker version 1.13.1, build 092cba3
root@openshift:/mnt/sda1/var/lib/boot2docker# pwd
/var/lib/boot2docker
root@openshift:/mnt/sda1/var/lib/boot2docker# cat > bootsync.sh
ifconfig eth0 192.168.0.30 netmask 255.255.255.0 broadcast 192.168.0.255 up
ip route add default via 192.168.0.1
root@openshift:/mnt/sda1/var/lib/boot2docker# cat bootsync.sh
ifconfig eth0 192.168.0.30 netmask 255.255.255.0 broadcast 192.168.0.255 up
ip route add default via 192.168.0.1
use ctrl-d
```
4. ocp-stop.sh (wait for merge in Hyper-v)
5. Start the machine in Hyper-V
6. UP the cluster again using below

`oc cluster up --image=registry.access.redhat.com/openshift3/ose --host-data-dir=/var/lib/boot2docker/ocp-data --docker-machine=openshift --host-config-dir=/var/lib/boot2docker/ocp-config --use-existing-config=true --host-pv-dir=/var/lib/boot2docker/ocp-pv`

**Comment by betazep** [comment]
@cgsk123

Great! Thanks for the complete instructions. :)

~b

**Comment by eschabell** [comment]
Resolved it seems.
