### ISSUE TITLE
--create-machine option cannot be used with Docker for Windows

### ISSUE THREAD

**Issue by sabre1041** [redhatdemocentral/ocp-install-demo#5]
Since docker for windows uses hyperv as its virtualization engine, this parameter cannot be used. 

Recommend a method to omit this flag when running `oc cluster up`

**Comment by eschabell** [comment]
To be honest, would need an init.bat file from you for this project first... :-)

**Comment by eschabell** [comment]
Did fix this for Linux too as it's not needed there.

**Comment by eschabell** [comment]
Any interest in putting together an init.bat for this?

**Comment by sabre1041** [comment]
@eschabell ill put it on my list
