### ISSUE TITLE
Docker Machine creation cert error

### ISSUE THREAD

**Issue by bfalor** [redhatdemocentral/ocp-install-demo#50]
When I run the ./init.sh script I get this error 

Running pre-create checks...
(openshift) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v1.13.1/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
Creating machine...
(openshift) Boot2Docker URL was explicitly set to "https://github.com/boot2docker/boot2docker/releases/download/v1.13.1/boot2docker.iso" at create time, so Docker Machine cannot upgrade this machine to the latest version.
(openshift) Downloading /Users/bfalor/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.13.1/boot2docker.iso...
Error creating machine: Error in driver during machine creation: Get https://github.com/boot2docker/boot2docker/releases/download/v1.13.1/boot2docker.iso: x509: certificate signed by unknown authority

**Comment by eschabell** [comment]
@bfalor have you tried pasting that url into your browser? Does it download an iso?

If so put it in your cache directory and re-run init.sh:

~/.docker/machine/cache/boot2docker.iso

**Comment by eschabell** [comment]
Closing for now, if need be reopen on gitlab where this project moved to: https://gitlab.com/redhatdemocentral/ocp-install-demo
