### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thunderguyy** [redhatdemocentral/ocp-install-demo#51]
Running pre-create checks...
Creating machine...
(openshift) Image cache directory does not exist, creating it at /root/.docker/machine/cache...
(openshift) Downloading /root/.docker/machine/cache/boot2docker.iso from file:///root/.docker/machine/cache/boot2docker.iso...
Error creating machine: Error in driver during machine creation: open /root/.docker/machine/cache/boot2docker.iso: no such file or directory

Error occurred during openshift docker machine creation...

Cleaning out existing 'openshift' machine...

About to remove openshift
WARNING: This action will delete both local reference and remote instance.
(openshift) Failed to fetch machine
Error removing host "openshift": unexpected EOF
Successfully removed openshift
Setting up OpenShift docker machine using kvm from url...

Running pre-create checks...
Creating machine...
(openshift) Downloading /root/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.13.1/boot2docker.iso...
(openshift) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(openshift) Failed to create the VM: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm
Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] invalid argument: could not find capabilities for domaintype=kvm

**Comment by eschabell** [comment]
This project moved to Gitlab, please try it again there and raise issue there if a problem:

https://gitlab.com/redhatdemocentral/ocp-install-demo
