### ISSUE TITLE
Install OpenShift on win10 issue

### ISSUE THREAD

**Issue by chiaoyiwang** [redhatdemocentral/ocp-install-demo#52]
The error is below:
Running pre-create checks...
Error with pre-create check: "Hyper-v commands have to be run as an Administrator"

Error occurred during openshift docker machine creation...

Cleaning out existing 'openshift' machine...

About to remove openshift
WARNING: This action will delete both local reference and remote instance.
Error removing host "openshift": Docker machine "openshift" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
Can't remove "openshift"
Setting up new OpenShift docker machine...
Running pre-create checks...
Error with pre-create check: "Hyper-v commands have to be run as an Administrator"

Problem with docker machine creation that I can't resolve, validate network configuration and/or please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new

How could I fix it? Thanks

**Comment by eschabell** [comment]
Two things here, I fixed the link above to point to where this project moved to (missed that on the migration), second, as a result please see https://gitlab.com/redhatdemocentral/ocp-install-demo/issues/new for new issues.

**Comment by eschabell** [comment]
@betazep could you, or would you mind taking a look over on:

https://gitlab.com/redhatdemocentral/ocp-install-demo/issues/52 

 Could use your expertise and didn't find a gitlab username for you yet. ;-)

**Comment by eschabell** [comment]
Update: June 2018 moved to Gitlab.
