### ISSUE TITLE
i'm a newbie sorry : 

### ISSUE THREAD

**Issue by renatotirone** [redhatdemocentral/ocp-install-demo#53]
these links are dead 
404
https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver63-image-stream.json

ranting rights to service catalog access...

cluster role "system:openshift:templateservicebroker-client" added: ["system:unauthenticated" "system:authenticated"]

Updating JBoss image streams...
error: unable to read URL "https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver63-image-stream.json", server reported 404 Not Found, status code=404

Problem with accessing JBoss BRMS 63 stream for OCP...

Trying again...

**Comment by eschabell** [comment]
No worries, this has moved and not updated / maintained here. 

README states - Update: June 2018 moved to Gitlab.

https://gitlab.com/redhatdemocentral/ocp-install-demo
