### ISSUE TITLE
The json path in init.sh are returning 404 not found exception

### ISSUE THREAD

**Issue by crajesh238** [redhatdemocentral/ocp-install-demo#55]
The http:// path for json files present in init.sh are returning null.

**Comment by crajesh238** [comment]
OLD URL : "https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver63-image-stream.json"

NEW URL : https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver63-image-stream.json

The new URL worked as I replaced master with release-3.10.

Once you fix it you can close the ticket.
The issue is with all the URLS present for master.

**Comment by eschabell** [comment]
@crajesh238, 

Thanks for the report, but  please see Readme for this project - "Update: June 2018 moved to [Gitlab](https://gitlab.com/redhatdemocentral/ocp-install-demo)."  

You'll find this problem fixed over at the [Gitlab project](https://gitlab.com/redhatdemocentral/ocp-install-demo).
