### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by gdwinco** [redhatdemocentral/ocp-install-demo#6]
This has worked previosly

Docker 1.12.3 (13776) Stable

OC client:
oc version
oc v3.3.1.3
kubernetes v1.3.0+52492b4
features: Basic-Auth
error: server took too long to respond with version information.

// output from init.sh
Trying again to install OSE with cluster up...

-- Checking OpenShift client ... OK
-- Create Docker machine ...
   Creating docker-machine openshift
-- Checking Docker client ... OK
-- Checking Docker version ... OK
-- Checking for existing OpenShift container ... OK
-- Checking for registry.access.redhat.com/openshift3/ose:v3.3.1.3 image ...
   Pulling image registry.access.redhat.com/openshift3/ose:v3.3.1.3
FAIL
   Error: error pulling Docker image registry.access.redhat.com/openshift3/ose:v3.3.1.3
   Caused By:
     Error: API error (500): {"message":"Get https://registry.access.redhat.com/v1/_ping: x509: certificate signed by unknown authority"}

Problem with installation that I can't resolve, please raise an issue and add error output:

   https://github.com/redhatdemocentral/ocp-install-demo/issues/new

**Comment by eschabell** [comment]
Same here... think that there is something wrong in the OpenShift registry.... let me ask around internally...

**Comment by gdwinco** [comment]
seems to be working again. Thx

**Comment by sabre1041** [comment]
@gdwinco There was an issue earlier this morning. It has since been resolved
