### ISSUE TITLE
init.sh issue with installing oc

### ISSUE THREAD

**Issue by ishuverma** [redhatdemocentral/ocp-install-demo#8]
I'm trying to install OCP on Mac. Running the init.sh, I got the following error:

./init.sh: line 72: oc: command not found
./init.sh: line 76: [: ==: unary operator expected
Version of installed OpenShift command line tools is ., must be v3.3 or higher...

I downloaded the oc cli from:
Download for Mac here: https://s3.amazonaws.com/oso-preview-docker-registry/client-tools/3.3/oc-3.3.1.3-1-macosx.tar.gz

Not sure if oc is installing correctly (log enclosed). None of the oc cli commands work and init.sh gives the same error as before.
[oc-install-log.txt](https://github.com/redhatdemocentral/ocp-install-demo/files/649748/oc-install-log.txt)

**Comment by sabre1041** [comment]
@ishuverma `oc` is a standalone executable. For other programs to make use of it, it must be added to the system PATH

**Comment by eschabell** [comment]
@sabre1041 This is failing to find oc and it should exit on line 72, not sure why it does not.... the error should go to /dev/null....

**Comment by ishuverma** [comment]
Setting the path to oc resolved the issue. Thanks.
