### ISSUE TITLE
Update documentation to specify "--insecure-registry 172.30.0.0/16" on Linux

### ISSUE THREAD

**Issue by jamesbuckett** [redhatdemocentral/ocp-install-demo#9]
Hello.
.
When running this on Ubuntu the Docker daemon needs to run with the argument : --insecure-registry 172.30.0.0/16

Could you update the documentation for Linux users :

"On Linux please ensure that the Docker daemon is running with the following argument:
        --insecure-registry 172.30.0.0/16"

**Comment by eschabell** [comment]
@jamesbuckett, thanks for the report... what determines that address for the registry? Is that for all users or is they dynamically determined based on your current network?

**Comment by eschabell** [comment]
Open if still want this to happen and answer question above...
